[theme]
base = "dark"
primaryColor = "#dc2626"
backgroundColor = "#0a0a0c"
secondaryBackgroundColor = "#121216"
textColor = "#f8fafc"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
